### ISSUE TITLE
Test is not working

### ISSUE THREAD

**Issue by Irene-GM** [tompollard/sammon#2]
Hi Tom,

Thanks for your code. I had similar problems as in the Issue #1 (https://github.com/tompollard/sammon/issues/1) and applying the suggestions to the code, it is working and providing the following image, which might be nice to add to the main page of the project. :-)
![iris](https://cloud.githubusercontent.com/assets/8654047/8057795/c75a0fca-0eb4-11e5-8bcb-810c90ef41ec.png)

What I can do now is making a pull request.

**Comment by Irene-GM** [comment]
Hey, I tried to create a pull request (first time, sorry), but I have no idea if you got it. I see your Sammon repository copied in my workspace, but with the modified file instead of the original. However, I have no idea if I have to do extra steps...

**Comment by tompollard** [comment]
Hey Irene,

Many thanks for looking at this. It looks like you made the pull request on your own forked repository, rather than my upstream one. You can make a new request using the button at: https://github.com/tompollard/sammon/pulls. Nice idea to include the figure :) Please could you contribute this with a pull request too?

Tom

**Comment by Irene-GM** [comment]
Hi Tom!

Thanks for your quick response. Please, check if I did correctly the pull request. I am totally new to this operation. Thanks!

**Comment by tompollard** [comment]
Great, thanks Irene, I got the pull request :) Will test and merge the request as soon as I get the chance!

**Comment by tompollard** [comment]
Thanks again @Irene-GM
